site_name: xTorch
theme:
  name: material  # looks clean and modern
nav:
  - Home: index.md
  - Install: installation.md
  - Tutorials:
      - Hello World: tutorials/hello_world.md
      - Settings: tutorials/settings.md